### ISSUE TITLE
Doesn't work with 1.0.2

### ISSUE THREAD

**Issue by badoualy** [NotBela/MyGoBot.org-Server-Emulator#1]
Nice idea, doesn't work with 1.0.2 though, I don't get the log line (request.url), so I guess something is wrong with the certificate

**Comment by NotBela** [comment]
Its working just fine fo me with 1.0.2. Did you included the line in your host file. You may also need admin rights to bind port 443.

**Comment by badoualy** [comment]
Ran it as admin, I did add the host line, but I but "Unhandled exception while attempting to authenticate"

**Comment by NotBela** [comment]
Ok. i think i missed to include one step. I will include that later this day. Hotfix:
Go to the Chrome Settings. Then under HTTPS click Manage Certs. Now click Import and import the cert.cert as a root cert or something like that.

**Comment by badoualy** [comment]
Hmm, tried that, changed nothing :/

**Comment by badoualy** [comment]
Ok it worked, when importing, i chose the wrong location (by default Personnal instead of root...)
