### ISSUE TITLE
Getting Stuck On "node index.js" 

### ISSUE THREAD

**Issue by KattNip** [NotBela/MyGoBot.org-Server-Emulator#13]
i seem to only be getting stuck on this command it just stays loading this command not displaying anything help would be much appreciated.

**Comment by NotBela** [comment]
what? which command? logs? screenshots?

**Comment by KattNip** [comment]
Ah so sorry it was the "node index.js" it was just stuck on loading the command. though i seemed to fix this issue by running the command then opening the GOBot which seemed to unfreeze this. probably had to do that in the first place and just being dumb. thanks

**Comment by NotBela** [comment]
ok
