### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by nitishgupta4291** [NotBela/MyGoBot.org-Server-Emulator#14]
this looks like a nice trick , thanks for sharing .

can you please give a step wise guide how to install this .

**Comment by captcrywolf** [comment]
bro Guide is  already given

**Comment by nitishgupta4291** [comment]
i get this error , please help

module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\nitish\Desktop\MyGoBot.org-Server-Emulator-m
aster\MyGoBot.org-Server-Emulator-master\index.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by captcrywolf** [comment]
@nitishgupta4291 bro same happened with me , do u have team viewer , i can help

**Comment by captcrywolf** [comment]
add ::1 mygobot.org in hosts file

**Comment by NotBela** [comment]
no, you didnt do npm i

**Comment by nitishgupta4291** [comment]
@captcrywolf  sure mate , I will try it . please tell me how can I connect with you if this doesn't work . team viewer would be great

@NotBela  how to run npm I command ??

**Comment by captcrywolf** [comment]
@nitishgupta4291 bro wen u create d new folder press shift + right click and click on Open command window here > den follow d instructions 
download node.js from d link , download .msi version of it

**Comment by nitishgupta4291** [comment]
@captcrywolf  can you help me using team viewer?

**Comment by nitishgupta4291** [comment]
I have done everything .. but I am not sure where I am doing it wrong.

**Comment by captcrywolf** [comment]
@nitishgupta4291 sure give me ur tv info i log in

**Comment by nitishgupta4291** [comment]
@captcrywolf  mailed you the credentials .. please log in

**Comment by captcrywolf** [comment]
@NotBela help bro , my pc got switched off , when i turned it on i am getting the NPM i error

**Comment by NotBela** [comment]
Watch #15
