### ISSUE TITLE
Error.. cannot load the index.js file.. Screenshot inside..

### ISSUE THREAD

**Issue by Pladetor** [NotBela/MyGoBot.org-Server-Emulator#16]
I did all the steps but when i write in the cmd: node index.js it returns an error..
I posted the screenshot of the error in here: http://prntscr.com/bzspwy
Please someone look and tell me what to do cuz i rly wanna fix it and get the bot to work for me.

**Comment by Pladetor** [comment]
I got it fixed but now it does'nt post any console out put after i write: node index.js /:
Any suggestions about how to fix it?

**Comment by NotBela** [comment]
So, i guess, you solved it.
