### ISSUE TITLE
node index.js not detecting bot?

### ISSUE THREAD

**Issue by PokemonXLX** [NotBela/MyGoBot.org-Server-Emulator#2]
node index.js not detecting bot?

**Comment by NotBela** [comment]
The node part is just the webserver. Heres how you can quick check if everything works:
- Start the node programm
- Then navigate to https://mygobot.org in your webbrowser.
- If you get any error like SSL then your certs arent working. if you get anything else, just post this here.

**Comment by TwoRoelio** [comment]
I'm using windows 7 and I see mygobot.org added to the trusted base certificates but if I run node index.js nothing is showing and also the website give me a ssl error.

Anyway great respect for your work.

**Comment by PokemonXLX** [comment]
The page is fine, no ssl errors, nothing. Maybe you should make a video of yourself doing this?
