### ISSUE TITLE
How to install p7b certificate in Windows 7

### ISSUE THREAD

**Issue by menshinobi** [NotBela/MyGoBot.org-Server-Emulator#21]
Hi, I tried to install the p7b file in my Windows 7 machine but should I install it under My User Account or Computer Account? A Youtube tutorial is really helpful please. Thank you very much!

**Comment by NotBela** [comment]
Your local accountshould be fine.

2016-08-10 10:32 GMT+02:00 menshinobi <notifications@github.com>:
