### ISSUE TITLE
getting this warning after typing 'npm i'. any idea how to fix this?

### ISSUE THREAD

**Issue by bet4234** [NotBela/MyGoBot.org-Server-Emulator#3]
npm WARN package.json mygobot-server-emulator@1.0.0 No repository field.

**Comment by PokemonXLX** [comment]
redownload mygobot and the zip files for the server emulator

**Comment by NotBela** [comment]
its just a waning. nothing critical. i will fix that later today.

**Comment by NotBela** [comment]
Fixed
