### ISSUE TITLE
it doesn't seem to be giving me the verification code do you know whats wrong?

### ISSUE THREAD

**Issue by bet4234** [NotBela/MyGoBot.org-Server-Emulator#4]

**Comment by NotBela** [comment]
what do you mean with verification code?

**Comment by jackhair** [comment]
The verification code for google.com/device is blank.

**Comment by bet4234** [comment]
yeah im getting a blank verification code "Goto: http://www.google.com/device & enter "

**Comment by NotBela** [comment]
ahh, thats not a problem related to this programm. Try to ask for support on there discord.

**Comment by NotBela** [comment]
#6
