### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by spok3y** [NotBela/MyGoBot.org-Server-Emulator#7]
at first when i imported it didnt find the file and then i changed the name of the file to cert.crt and then i found it.
i finished all and then i typed in the console node index.js and this is what comes:
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Stav\Desktop\תיקיה חדשה\index.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by spok3y** [comment]
nvm i understand what was my problem i didnt type "i" with the npm but now i have another thing

C:\Users\Stav\Desktop\MyGoBot.org-Server-Emulator-master>certmgr

C:\Users\Stav\Desktop\MyGoBot.org-Server-Emulator-master>npm i
request@2.74.0 node_modules\request
├── tunnel-agent@0.4.3
├── aws-sign2@0.6.0
├── oauth-sign@0.8.2
├── forever-agent@0.6.1
├── caseless@0.11.0
├── is-typedarray@1.0.0
├── stringstream@0.0.5
├── aws4@1.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.3.1
├── qs@6.2.1
├── node-uuid@1.4.7
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.11 (mime-db@1.23.0)
├── form-data@1.0.0-rc4 (async@1.5.2)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── bl@1.1.2 (readable-stream@2.0.6)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.3.0, sshpk@1.9.0)
└── har-validator@2.0.6 (pinkie-promise@2.0.1, commander@2.9.0, chalk@1.1.3, is-my-json-valid@2.13.1)

C:\Users\Stav\Desktop\MyGoBot.org-Server-Emulator-master>node index.js
i did it like 3 times but in the first time i got the Command Prompts and now it doesnt work. help me

**Comment by NotBela** [comment]
did you added the certs in the certmgr?
