### ISSUE TITLE
Failed to authenticate 

### ISSUE THREAD

**Issue by constantlyconfused** [NotBela/MyGoBot.org-Server-Emulator#9]
Hello there,

I've followed all the steps, here's the certificate in the correct folder: http://puu.sh/qhCI1/f9f071297d.png
Here's my edited hosts file: http://puu.sh/qhCKh/bed3bc4151
Here's the command in the CMD: http://puu.sh/qhCLd/2e10621320.png
I have also typed "npm i" into command prompt like so: http://puu.sh/qhCQM/b50e885488.png

This is the issue I am greeted with when I type in a token: http://puu.sh/qhCSd/66844e83e3.png

Anyone have a similar issue?

**Comment by NotBela** [comment]
Did you added the cert as root cert?

**Comment by constantlyconfused** [comment]
I did as you said, and added it into the "Trusted Root Certification Authorities". http://puu.sh/qhExC/b1227bcae4.png

**Comment by jabibi** [comment]
Same here
I tried with previous version 1.0.3 and it worked like a charm, but not with 1.0.4

**Comment by iExad** [comment]
Maybe all problems in version update checking?

**Comment by NotBela** [comment]
Still works with 1.0.4. They havent changed the login system.
